# قائمة العملات المفلترة شرعياً (من قائمة المستخدم على DropsTab)
# رمز التداول بصيغة KuCoin: SYMBOL-USDT
# ملاحظة: هذه القائمة تصنيف المستخدم الشخصي وليست فتوى معتمدة.
# يُنصح بمراجعة كل مشروع فردياً، خصوصاً عملات الخصوصية (ZEC, XMR)
# التي قد تحتاج نقاشاً فقهياً إضافياً بسبب طبيعة إخفاء المعاملات.

WATCHLIST = [
    "BTC-USDT",
    "ETH-USDT",
    "BNB-USDT",
    "XRP-USDT",
    "SOL-USDT",
    "TRX-USDT",
    "ZEC-USDT",
    "XLM-USDT",
    "XMR-USDT",
    "ADA-USDT",
    "LINK-USDT",
    "BCH-USDT",
    "GRAM-USDT",
    "LTC-USDT",
    "SUI-USDT",
    "AVAX-USDT",
    "NEAR-USDT",
    "TAO-USDT",
    "DOT-USDT",
    "WLD-USDT",
    "ICP-USDT",
    "ETC-USDT",
    "POL-USDT",
    "ATOM-USDT",
    "QNT-USDT",
    "UB-USDT",
    "AIO-USDT",
    "H-USDT",
    "XLM-USDT",
    "HBAR-USDT",
    "AKE-USDT",
    "ZAMA-USDT",
    "GWEI-USDT",
    "PYTH-USDT",
    "DGB-USDT",
    "XAUT-USDT",
    "KITE-USDT",
    "ORDI-USDT",
    "RENDER-USDT",
    "FET-USDT",
    "XTZ-USDT",
    "ARB-USDT",
    "ATOM-USDT",
    "AVAX-USDT",
    "DCR-USDT",
    "ZEN-USDT",
]
